add Book model, CRUD and RSpec tests
iryna-borniak/book_store pull request #1
Opened 2023-10-13 18:37 UTC by iryna-borniak

2023-10-24 07:38 UTC, loqimean reviewed
ті ж коменти, що і [тут](https://github.com/fh0enix/books_reader/pull/1) також

2023-10-24 07:38 UTC, loqimean commented on app/controllers/books_controller.rb
> +    @books = Book.ordered_by_title
collection

2023-10-24 07:38 UTC, loqimean commented on app/helpers/application_helper.rb
цей хелпер най буде по-замовчуванню

2023-10-24 07:38 UTC, loqimean commented on app/models/book.rb
> +  scope :ordered_by_title, -> { order(title: :asc) }
`asc` ordering is setted by default

2023-10-24 07:38 UTC, loqimean commented on app/views/books/_form.html.erb
> +<%= simple_form_for book, html: { class: "contents" } do |form| %>
а де шлях, на який ти посилаєш форму?

2023-10-24 07:38 UTC, loqimean commented on app/views/books/index.html.erb
> +  <%= render "shared/notice" %>
це рендери відразу в лейауті

2023-10-24 07:38 UTC, loqimean commented on app/views/books/show.html.erb
> +    <%= render "shared/notice" %>
от знову повторюється

2023-10-24 07:38 UTC, loqimean commented on app/views/shared/_notice.html.erb
> +<% if notice.present? %>
а ворнінг? а ерор? не гуд, рендери флеш

2023-10-28 22:47 UTC, iryna-borniak commented on app/controllers/books_controller.rb
> +    @books = Book.ordered_by_title
fixed

2023-10-28 23:05 UTC, iryna-borniak commented on app/models/book.rb
> +  scope :ordered_by_title, -> { order(title: :asc) }
fixed

2023-10-29 00:24 UTC, iryna-borniak commented on app/views/books/_form.html.erb
> +<%= simple_form_for book, html: { class: "contents" } do |form| %>
fixed

2023-10-29 05:03 UTC, iryna-borniak commented on app/views/books/show.html.erb
> +    <%= render "shared/notice" %>
fixed

2023-10-29 05:04 UTC, iryna-borniak commented on app/views/books/index.html.erb
> +  <%= render "shared/notice" %>
fixed

2023-10-29 05:07 UTC, iryna-borniak commented on app/views/shared/_notice.html.erb
> +<% if notice.present? %>
fixed

2023-10-29 05:22 UTC, iryna-borniak commented on app/helpers/application_helper.rb
fixed

2023-11-01 07:52 UTC, loqimean requested changes

2023-11-01 07:52 UTC, loqimean commented on db/seeds.rb
а де сіди?))

2023-11-01 07:52 UTC, loqimean commented on lib/templates/erb/scaffold/_form.html.erb
навіщо це?)

2023-11-01 07:52 UTC, loqimean commented on spec/requests/books_spec.rb
> +        expect(flash[:notice]).to eq("Book was successfully updated.")
їх не тре розділяти окремо

2023-11-01 07:52 UTC, loqimean commented on spec/requests/books_spec.rb
> +      expect(flash[:alert]).to eq("Book was successfully destroyed.")
```suggestion
      expect(response).to redirect_to(books_url)
      expect(flash[:alert]).to eq("Book was successfully destroyed.")
```

2023-11-01 15:57 UTC, iryna-borniak commented on db/seeds.rb
fixed

2023-11-01 15:58 UTC, iryna-borniak commented on lib/templates/erb/scaffold/_form.html.erb
fixed

2023-11-01 15:58 UTC, iryna-borniak commented on spec/requests/books_spec.rb
> +        expect(flash[:notice]).to eq("Book was successfully updated.")
fixed

2023-11-01 15:58 UTC, iryna-borniak commented on spec/requests/books_spec.rb
> +      expect(flash[:alert]).to eq("Book was successfully destroyed.")
fixed

2023-11-01 17:33 UTC, loqimean approved these changes

2023-11-01 20:08 UTC, merged