Devise
iryna-borniak/book_store pull request #2
Opened 2023-11-10 04:32 UTC by iryna-borniak

2023-11-15 18:34 UTC, loqimean requested changes

2023-11-15 18:34 UTC, loqimean commented on app/assets/stylesheets/utilities.css
> +}
а що це таке і чому воно тут?)

2023-11-15 18:34 UTC, loqimean commented on app/views/devise/registrations/new.html.erb
> +    <%= f.error_notification %>
це не тре, сімпл-форм сам виводить нотифікації

2023-11-15 18:34 UTC, loqimean commented on config/routes.rb
> +  end
це тре в самий верх перемістити

2023-11-15 18:34 UTC, loqimean commented on spec/models/user_spec.rb
> +  let(:invalid_attribute) { FactoryBot.attributes_for(:user, :wrong_password) }
не треба клас факторі-бота передавати, він тут не обовʼязковий

2023-11-15 18:34 UTC, loqimean commented on spec/requests/users_registrations_spec.rb
> +  let(:invalid_attributes) { FactoryBot.attributes_for(:user, :wrong_password) }
те ж

2023-11-18 22:48 UTC, iryna-borniak commented on app/assets/stylesheets/utilities.css
> +}
кастомні градієнти; перенесла в tailwind.config.js

2023-11-18 23:33 UTC, iryna-borniak commented on spec/requests/users_registrations_spec.rb
> +  let(:invalid_attributes) { FactoryBot.attributes_for(:user, :wrong_password) }
done

2023-11-18 23:34 UTC, iryna-borniak commented on spec/models/user_spec.rb
> +  let(:invalid_attribute) { FactoryBot.attributes_for(:user, :wrong_password) }
done

2023-11-18 23:34 UTC, iryna-borniak commented on config/routes.rb
> +  end
done

2023-11-22 08:37 UTC, loqimean requested changes

2023-11-22 08:37 UTC, loqimean commented on app/assets/stylesheets/components/main.css
> +    opacity: 0.2;
пропиши юзаючи теілвінд

2023-11-22 13:32 UTC, iryna-borniak commented on app/assets/stylesheets/components/main.css
> +    opacity: 0.2;
перенесла: https://github.com/iryna-borniak/book_store/pull/3/commits/23c9f00db931d97103fe623ca4e319bb3d398ce6

2023-11-28 07:25 UTC, loqimean approved these changes

2023-11-29 18:40 UTC, merged