Active storage
iryna-borniak/book_store pull request #3
Opened 2023-11-20 19:56 UTC by iryna-borniak

2023-11-22 09:28 UTC, loqimean requested changes

2023-11-22 09:28 UTC, loqimean commented on app/assets/stylesheets/components/main.css
> +    @apply mx-auto md:max-w-[980px] w-full px-5;
щось це `max-w-[980px]` часто повторюється, винеси в конфіги

2023-11-22 09:28 UTC, loqimean commented on app/assets/stylesheets/components/show.css
> +    @apply mx-auto md:max-w-[980px] w-full px-5 flex flex-wrap gap-10;
і тут

2023-11-22 13:28 UTC, iryna-borniak commented on app/assets/stylesheets/components/main.css
> +    @apply mx-auto md:max-w-[980px] w-full px-5;
done

2023-11-22 13:28 UTC, iryna-borniak commented on app/assets/stylesheets/components/show.css
> +    @apply mx-auto md:max-w-[980px] w-full px-5 flex flex-wrap gap-10;
done

2023-11-28 07:27 UTC, loqimean approved these changes

2023-11-29 18:40 UTC, merged